// Lista curada de CNAEs mais usados no Brasil (subclasses 7 dígitos).
// Ampliar sob demanda. Formato: { code, label }.

export interface CnaeOption {
  code: string;
  label: string;
}

export const CNAE_LIST: CnaeOption[] = [
  { code: "6920601", label: "Contabilidade / Escritórios contábeis" },
  { code: "6911701", label: "Advocacia / Escritórios de advocacia" },
  { code: "6201501", label: "Desenvolvimento de programas de computador sob encomenda" },
  { code: "6202300", label: "Desenvolvimento e licenciamento de software customizável" },
  { code: "6203100", label: "Desenvolvimento e licenciamento de software não-customizável" },
  { code: "6204000", label: "Consultoria em tecnologia da informação" },
  { code: "6209100", label: "Suporte técnico e manutenção em TI" },
  { code: "6311900", label: "Tratamento de dados / hospedagem" },
  { code: "8299707", label: "Salas e escritórios compartilhados (coworking)" },
  { code: "7020400", label: "Consultoria em gestão empresarial" },
  { code: "7319002", label: "Promoção de vendas" },
  { code: "7311400", label: "Agências de publicidade" },
  { code: "7312200", label: "Agenciamento de espaços para publicidade" },
  { code: "7410202", label: "Design de interiores" },
  { code: "8630501", label: "Clínica médica" },
  { code: "8630502", label: "Clínica odontológica" },
  { code: "8630503", label: "Clínica psicológica" },
  { code: "8650099", label: "Outras atividades de profissionais da saúde" },
  { code: "8610101", label: "Hospitais" },
  { code: "8720401", label: "Atividades de assistência a idosos" },
  { code: "8511200", label: "Educação infantil" },
  { code: "8513900", label: "Ensino fundamental" },
  { code: "8520100", label: "Ensino médio" },
  { code: "8531700", label: "Educação superior — graduação" },
  { code: "8599604", label: "Treinamento em desenvolvimento profissional e gerencial" },
  { code: "8592999", label: "Ensino de arte e cultura" },
  { code: "4711302", label: "Supermercados" },
  { code: "4711301", label: "Hipermercados" },
  { code: "4712100", label: "Minimercados / mercearias" },
  { code: "4721102", label: "Padarias e confeitarias" },
  { code: "5611201", label: "Restaurantes e similares" },
  { code: "5611203", label: "Lanchonetes / casas de chá" },
  { code: "5611204", label: "Bares e outros estabelecimentos com serviço de bebidas" },
  { code: "5620104", label: "Fornecimento de alimentos preparados / marmitex" },
  { code: "4930202", label: "Transporte rodoviário de carga intermunicipal" },
  { code: "4930201", label: "Transporte rodoviário de carga municipal" },
  { code: "4923002", label: "Transporte por táxi" },
  { code: "4929999", label: "Outros transportes rodoviários de passageiros" },
  { code: "5229099", label: "Outras atividades auxiliares dos transportes" },
  { code: "4120400", label: "Construção de edifícios" },
  { code: "4211101", label: "Construção de rodovias e ferrovias" },
  { code: "4321500", label: "Instalação e manutenção elétrica" },
  { code: "4322301", label: "Instalações hidráulicas / sanitárias / gás" },
  { code: "4330404", label: "Serviços de pintura de edifícios" },
  { code: "1091102", label: "Fabricação de produtos de padaria e confeitaria" },
  { code: "1412601", label: "Confecção de peças de vestuário" },
  { code: "2542000", label: "Fabricação de artigos de serralheria" },
  { code: "2599399", label: "Fabricação de produtos de metal diversos" },
  { code: "2829199", label: "Fabricação de máquinas e equipamentos de uso geral" },
  { code: "3299099", label: "Indústrias diversas" },
  { code: "4520001", label: "Serviços de manutenção e reparação mecânica de veículos" },
  { code: "4520005", label: "Serviços de lavagem, lubrificação e polimento de veículos" },
  { code: "4530703", label: "Comércio a varejo de peças e acessórios para veículos" },
  { code: "4511101", label: "Comércio a varejo de automóveis novos" },
  { code: "4511102", label: "Comércio a varejo de automóveis usados" },
  { code: "4649408", label: "Comércio atacadista de produtos de higiene, limpeza e conservação" },
  { code: "4691500", label: "Comércio atacadista de mercadorias em geral" },
  { code: "4744099", label: "Comércio varejista de materiais de construção" },
  { code: "4755502", label: "Comércio varejista de artigos de armarinho" },
  { code: "4761003", label: "Comércio varejista de artigos de papelaria" },
  { code: "4771701", label: "Comércio varejista de produtos farmacêuticos (drogarias)" },
  { code: "4772500", label: "Comércio varejista de cosméticos e perfumaria" },
  { code: "4781400", label: "Comércio varejista de vestuário" },
  { code: "4782201", label: "Comércio varejista de calçados" },
  { code: "9602501", label: "Cabeleireiros / manicure / pedicure" },
  { code: "9602502", label: "Atividades de estética" },
  { code: "9313100", label: "Academias de esportes / musculação" },
  { code: "9319101", label: "Produção e promoção de eventos esportivos" },
  { code: "5510801", label: "Hotéis" },
  { code: "5510802", label: "Apart-hotéis" },
  { code: "5590699", label: "Outros meios de hospedagem" },
  { code: "7911200", label: "Agências de viagens" },
  { code: "7912100", label: "Operadores turísticos" },
  { code: "9511800", label: "Reparação e manutenção de computadores" },
  { code: "9512600", label: "Reparação e manutenção de equipamentos de comunicação" },
  { code: "9529106", label: "Reparação de joias" },
  { code: "8121400", label: "Limpeza em prédios e em domicílios" },
  { code: "8011101", label: "Atividades de vigilância e segurança privada" },
  { code: "8020000", label: "Atividades de monitoramento de sistemas de segurança" },
  { code: "8219999", label: "Preparação de documentos e serviços especializados de apoio administrativo" },
  { code: "7820500", label: "Locação de mão de obra temporária" },
  { code: "7810800", label: "Seleção e agenciamento de mão de obra" },
  { code: "8291100", label: "Cobrança e informações cadastrais" },
  { code: "6821801", label: "Corretagem na compra e venda / avaliação de imóveis" },
  { code: "6822600", label: "Gestão e administração de imóveis" },
  { code: "6810201", label: "Compra e venda de imóveis próprios" },
  { code: "6810202", label: "Aluguel de imóveis próprios" },
  { code: "3811400", label: "Coleta de resíduos não perigosos" },
  { code: "3821100", label: "Tratamento e disposição de resíduos não perigosos" },
  { code: "3900500", label: "Descontaminação e outros serviços de gestão de resíduos" },
  { code: "0161003", label: "Serviço de preparação de terreno / cultivo / colheita" },
  { code: "0155501", label: "Criação de frangos para corte" },
  { code: "0151201", label: "Criação de bovinos para corte" },
  { code: "0113000", label: "Cultivo de cana-de-açúcar" },
  { code: "6499999", label: "Outras atividades de serviços financeiros" },
  { code: "6613400", label: "Administração de cartões de crédito" },
  { code: "6619399", label: "Outras atividades auxiliares dos serviços financeiros" },
  { code: "6621501", label: "Peritos e avaliadores de seguros" },
  { code: "6622300", label: "Corretores e agentes de seguros / previdência complementar" },
];

export function searchCnae(q: string): CnaeOption[] {
  const s = q.trim().toLowerCase();
  if (!s) return CNAE_LIST.slice(0, 30);
  return CNAE_LIST.filter(
    (c) => c.code.includes(s) || c.label.toLowerCase().includes(s),
  ).slice(0, 30);
}