import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { PageHeader } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { upsertIcp } from "@/lib/icp.functions";
const fields = [["desired_cnaes","CNAEs desejados","lista",20],["forbidden_cnaes","CNAEs proibidos","lista",0],["segments","Segmentos","lista",10],["states","UFs","lista",5],["cities","Cidades","lista",5],["portes","Portes","lista",10],["min_capital_social","Capital social mínimo (R$)","número",8],["min_faturamento","Faturamento estimado mínimo (R$)","número",8],["min_employees","Funcionários mínimos","número",0],["max_employees","Funcionários máximos","número",0],["situacao_cadastral","Situação cadastral","lista",8],["min_company_age_years","Idade mínima (anos)","número",6],["desired_roles","Cargos desejados","lista",0],["forbidden_roles","Cargos proibidos","lista",0]] as const;
export const Route = createFileRoute("/_authenticated/ideal-customer-profiles/new")({ component: NewIcpPage });
function NewIcpPage(){const nav=useNavigate(),save=useServerFn(upsertIcp);const[name,setName]=useState(""),[description,setDescription]=useState(""),[product,setProduct]=useState(""),[score,setScore]=useState(80),[criteria,setCriteria]=useState<Record<string,string>>({}),[weights,setWeights]=useState<Record<string,number>>({}),[required,setRequired]=useState<string[]>([]),[saving,setSaving]=useState(false);const submit=async()=>{setSaving(true);try{const data:any={};for(const[k,,type]of fields){const v=criteria[k];if(v)data[k]=type==="lista"?v.split(",").map(x=>x.trim()).filter(Boolean):Number(v)}await save({data:{name,description:description||null,product_or_service:product||null,minimum_score:score,status:"active",criteria_json:{...data,required_criteria:required},weights_json:weights}});toast.success("ICP criado com sucesso.");nav({to:"/ideal-customer-profiles"})}catch(e){toast.error((e as Error).message)}finally{setSaving(false)}};return <div className="w-full space-y-5"><PageHeader title="Novo ICP" description="Defina critérios e pesos para qualificar empresas." action={<Button variant="outline" onClick={()=>nav({to:"/ideal-customer-profiles"})}>Voltar</Button>}/><Card className="w-full"><CardHeader><CardTitle>Informações principais</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div><Label>Nome</Label><Input value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Score mínimo (%)</Label><Input type="number" value={score} onChange={e=>setScore(Number(e.target.value))}/></div></div><div><Label>Descrição</Label><Textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></div><div><Label>Produto ou serviço a oferecer</Label><Input value={product} onChange={e=>setProduct(e.target.value)}/></div><div className="border-t pt-5"><h2 className="mb-4 text-base font-semibold">Critérios e pesos</h2><div className="grid gap-4 md:grid-cols-2">{fields.map(([key,label,type,defaultWeight])=><div key={key} className="space-y-1.5"><div className="flex items-center justify-between gap-2"><Label>{label}</Label><div className="flex items-center gap-2 text-xs"><label><input type="checkbox" checked={required.includes(key)} onChange={e=>setRequired(x=>e.target.checked?[...x,key]:x.filter(i=>i!==key))}/> obrigatório</label><Input className="h-7 w-14" type="number" value={weights[key]??defaultWeight} onChange={e=>setWeights({...weights,[key]:Number(e.target.value)})}/></div></div><Input placeholder={type==="lista"?"valor 1, valor 2":"número"} value={criteria[key]??""} onChange={e=>setCriteria({...criteria,[key]:e.target.value})}/></div>)}</div></div><div className="flex flex-col gap-2 border-t pt-5 sm:flex-row sm:justify-end"><Button variant="outline" onClick={()=>nav({to:"/ideal-customer-profiles"})}>Cancelar</Button><Button disabled={!name||saving} onClick={submit}>{saving?"Salvando...":"Criar ICP"}</Button></div></CardContent></Card></div>}
