/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentBuilderRouteImport } from './routes/_authenticated.agent-builder'
import { Route as AuthenticatedAgentOptimizationRouteImport } from './routes/_authenticated.agent-optimization'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated.agents'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedCadencesRouteImport } from './routes/_authenticated.cadences'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated.calls'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated.conversations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated.diagnostics'
import { Route as AuthenticatedIdealCustomerProfilesRouteImport } from './routes/_authenticated.ideal-customer-profiles'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated.import'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated.knowledge'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated.leads'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated.marketplace'
import { Route as AuthenticatedMyCalendarRouteImport } from './routes/_authenticated.my-calendar'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated.products'
import { Route as AuthenticatedProspectingRouteImport } from './routes/_authenticated.prospecting'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedAdminSaasRouteImport } from './routes/_authenticated.admin.saas'
import { Route as AuthenticatedIdealCustomerProfilesNewRouteImport } from './routes/_authenticated.ideal-customer-profiles.new'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated.leads.index'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated.leads.$id'
import { Route as AuthenticatedSettingsProvidersRouteImport } from './routes/_authenticated.settings.providers'
import { Route as ApiPublicInboundLeadRouteImport } from './routes/api/public/inbound-lead'
import { Route as ApiPublicCronCadenceTickRouteImport } from './routes/api/public/cron/cadence-tick'
import { Route as ApiPublicCronCalendarSyncRouteImport } from './routes/api/public/cron/calendar-sync'
import { Route as ApiPublicCronMeetingFollowupRouteImport } from './routes/api/public/cron/meeting-followup'
import { Route as ApiPublicCronRecoverLostRouteImport } from './routes/api/public/cron/recover-lost'
import { Route as ApiPublicCronReengageRouteImport } from './routes/api/public/cron/reengage'
import { Route as ApiPublicOrbitWebhookRouteImport } from './routes/api/public/orbit.webhook'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicCalendarOauthCallbackRouteImport } from './routes/api/public/calendar/oauth/callback'
import { Route as ApiPublicEmailOauthCallbackRouteImport } from './routes/api/public/email/oauth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentBuilderRoute =
  AuthenticatedAgentBuilderRouteImport.update({
    id: '/agent-builder',
    path: '/agent-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentOptimizationRoute =
  AuthenticatedAgentOptimizationRouteImport.update({
    id: '/agent-optimization',
    path: '/agent-optimization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadencesRoute = AuthenticatedCadencesRouteImport.update({
  id: '/cadences',
  path: '/cadences',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIdealCustomerProfilesRoute =
  AuthenticatedIdealCustomerProfilesRouteImport.update({
    id: '/ideal-customer-profiles',
    path: '/ideal-customer-profiles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyCalendarRoute = AuthenticatedMyCalendarRouteImport.update({
  id: '/my-calendar',
  path: '/my-calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectingRoute =
  AuthenticatedProspectingRouteImport.update({
    id: '/prospecting',
    path: '/prospecting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSaasRoute = AuthenticatedAdminSaasRouteImport.update({
  id: '/admin/saas',
  path: '/admin/saas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdealCustomerProfilesNewRoute =
  AuthenticatedIdealCustomerProfilesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedIdealCustomerProfilesRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedSettingsProvidersRoute =
  AuthenticatedSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const ApiPublicInboundLeadRoute = ApiPublicInboundLeadRouteImport.update({
  id: '/api/public/inbound-lead',
  path: '/api/public/inbound-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCadenceTickRoute =
  ApiPublicCronCadenceTickRouteImport.update({
    id: '/api/public/cron/cadence-tick',
    path: '/api/public/cron/cadence-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCalendarSyncRoute =
  ApiPublicCronCalendarSyncRouteImport.update({
    id: '/api/public/cron/calendar-sync',
    path: '/api/public/cron/calendar-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMeetingFollowupRoute =
  ApiPublicCronMeetingFollowupRouteImport.update({
    id: '/api/public/cron/meeting-followup',
    path: '/api/public/cron/meeting-followup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRecoverLostRoute =
  ApiPublicCronRecoverLostRouteImport.update({
    id: '/api/public/cron/recover-lost',
    path: '/api/public/cron/recover-lost',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReengageRoute = ApiPublicCronReengageRouteImport.update({
  id: '/api/public/cron/reengage',
  path: '/api/public/cron/reengage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrbitWebhookRoute = ApiPublicOrbitWebhookRouteImport.update({
  id: '/api/public/orbit/webhook',
  path: '/api/public/orbit/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarOauthCallbackRoute =
  ApiPublicCalendarOauthCallbackRouteImport.update({
    id: '/api/public/calendar/oauth/callback',
    path: '/api/public/calendar/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailOauthCallbackRoute =
  ApiPublicEmailOauthCallbackRouteImport.update({
    id: '/api/public/email/oauth/callback',
    path: '/api/public/email/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent-builder': typeof AuthenticatedAgentBuilderRoute
  '/agent-optimization': typeof AuthenticatedAgentOptimizationRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cadences': typeof AuthenticatedCadencesRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/ideal-customer-profiles': typeof AuthenticatedIdealCustomerProfilesRouteWithChildren
  '/import': typeof AuthenticatedImportRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/my-calendar': typeof AuthenticatedMyCalendarRoute
  '/products': typeof AuthenticatedProductsRoute
  '/prospecting': typeof AuthenticatedProspectingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/admin/saas': typeof AuthenticatedAdminSaasRoute
  '/ideal-customer-profiles/new': typeof AuthenticatedIdealCustomerProfilesNewRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/settings/providers': typeof AuthenticatedSettingsProvidersRoute
  '/api/public/inbound-lead': typeof ApiPublicInboundLeadRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/api/public/cron/cadence-tick': typeof ApiPublicCronCadenceTickRoute
  '/api/public/cron/calendar-sync': typeof ApiPublicCronCalendarSyncRoute
  '/api/public/cron/meeting-followup': typeof ApiPublicCronMeetingFollowupRoute
  '/api/public/cron/recover-lost': typeof ApiPublicCronRecoverLostRoute
  '/api/public/cron/reengage': typeof ApiPublicCronReengageRoute
  '/api/public/orbit/webhook': typeof ApiPublicOrbitWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/calendar/oauth/callback': typeof ApiPublicCalendarOauthCallbackRoute
  '/api/public/email/oauth/callback': typeof ApiPublicEmailOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent-builder': typeof AuthenticatedAgentBuilderRoute
  '/agent-optimization': typeof AuthenticatedAgentOptimizationRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cadences': typeof AuthenticatedCadencesRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/ideal-customer-profiles': typeof AuthenticatedIdealCustomerProfilesRouteWithChildren
  '/import': typeof AuthenticatedImportRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/my-calendar': typeof AuthenticatedMyCalendarRoute
  '/products': typeof AuthenticatedProductsRoute
  '/prospecting': typeof AuthenticatedProspectingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/admin/saas': typeof AuthenticatedAdminSaasRoute
  '/ideal-customer-profiles/new': typeof AuthenticatedIdealCustomerProfilesNewRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/settings/providers': typeof AuthenticatedSettingsProvidersRoute
  '/api/public/inbound-lead': typeof ApiPublicInboundLeadRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/api/public/cron/cadence-tick': typeof ApiPublicCronCadenceTickRoute
  '/api/public/cron/calendar-sync': typeof ApiPublicCronCalendarSyncRoute
  '/api/public/cron/meeting-followup': typeof ApiPublicCronMeetingFollowupRoute
  '/api/public/cron/recover-lost': typeof ApiPublicCronRecoverLostRoute
  '/api/public/cron/reengage': typeof ApiPublicCronReengageRoute
  '/api/public/orbit/webhook': typeof ApiPublicOrbitWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/calendar/oauth/callback': typeof ApiPublicCalendarOauthCallbackRoute
  '/api/public/email/oauth/callback': typeof ApiPublicEmailOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agent-builder': typeof AuthenticatedAgentBuilderRoute
  '/_authenticated/agent-optimization': typeof AuthenticatedAgentOptimizationRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/cadences': typeof AuthenticatedCadencesRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/ideal-customer-profiles': typeof AuthenticatedIdealCustomerProfilesRouteWithChildren
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/my-calendar': typeof AuthenticatedMyCalendarRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/prospecting': typeof AuthenticatedProspectingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/admin/saas': typeof AuthenticatedAdminSaasRoute
  '/_authenticated/ideal-customer-profiles/new': typeof AuthenticatedIdealCustomerProfilesNewRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/settings/providers': typeof AuthenticatedSettingsProvidersRoute
  '/api/public/inbound-lead': typeof ApiPublicInboundLeadRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/api/public/cron/cadence-tick': typeof ApiPublicCronCadenceTickRoute
  '/api/public/cron/calendar-sync': typeof ApiPublicCronCalendarSyncRoute
  '/api/public/cron/meeting-followup': typeof ApiPublicCronMeetingFollowupRoute
  '/api/public/cron/recover-lost': typeof ApiPublicCronRecoverLostRoute
  '/api/public/cron/reengage': typeof ApiPublicCronReengageRoute
  '/api/public/orbit/webhook': typeof ApiPublicOrbitWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/calendar/oauth/callback': typeof ApiPublicCalendarOauthCallbackRoute
  '/api/public/email/oauth/callback': typeof ApiPublicEmailOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agent-builder'
    | '/agent-optimization'
    | '/agents'
    | '/billing'
    | '/cadences'
    | '/calls'
    | '/conversations'
    | '/dashboard'
    | '/diagnostics'
    | '/ideal-customer-profiles'
    | '/import'
    | '/knowledge'
    | '/leads'
    | '/marketplace'
    | '/my-calendar'
    | '/products'
    | '/prospecting'
    | '/settings'
    | '/users'
    | '/admin/saas'
    | '/ideal-customer-profiles/new'
    | '/leads/$id'
    | '/settings/providers'
    | '/api/public/inbound-lead'
    | '/leads/'
    | '/api/public/cron/cadence-tick'
    | '/api/public/cron/calendar-sync'
    | '/api/public/cron/meeting-followup'
    | '/api/public/cron/recover-lost'
    | '/api/public/cron/reengage'
    | '/api/public/orbit/webhook'
    | '/api/public/whatsapp/webhook'
    | '/api/public/calendar/oauth/callback'
    | '/api/public/email/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agent-builder'
    | '/agent-optimization'
    | '/agents'
    | '/billing'
    | '/cadences'
    | '/calls'
    | '/conversations'
    | '/dashboard'
    | '/diagnostics'
    | '/ideal-customer-profiles'
    | '/import'
    | '/knowledge'
    | '/marketplace'
    | '/my-calendar'
    | '/products'
    | '/prospecting'
    | '/settings'
    | '/users'
    | '/admin/saas'
    | '/ideal-customer-profiles/new'
    | '/leads/$id'
    | '/settings/providers'
    | '/api/public/inbound-lead'
    | '/leads'
    | '/api/public/cron/cadence-tick'
    | '/api/public/cron/calendar-sync'
    | '/api/public/cron/meeting-followup'
    | '/api/public/cron/recover-lost'
    | '/api/public/cron/reengage'
    | '/api/public/orbit/webhook'
    | '/api/public/whatsapp/webhook'
    | '/api/public/calendar/oauth/callback'
    | '/api/public/email/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agent-builder'
    | '/_authenticated/agent-optimization'
    | '/_authenticated/agents'
    | '/_authenticated/billing'
    | '/_authenticated/cadences'
    | '/_authenticated/calls'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostics'
    | '/_authenticated/ideal-customer-profiles'
    | '/_authenticated/import'
    | '/_authenticated/knowledge'
    | '/_authenticated/leads'
    | '/_authenticated/marketplace'
    | '/_authenticated/my-calendar'
    | '/_authenticated/products'
    | '/_authenticated/prospecting'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/admin/saas'
    | '/_authenticated/ideal-customer-profiles/new'
    | '/_authenticated/leads/$id'
    | '/_authenticated/settings/providers'
    | '/api/public/inbound-lead'
    | '/_authenticated/leads/'
    | '/api/public/cron/cadence-tick'
    | '/api/public/cron/calendar-sync'
    | '/api/public/cron/meeting-followup'
    | '/api/public/cron/recover-lost'
    | '/api/public/cron/reengage'
    | '/api/public/orbit/webhook'
    | '/api/public/whatsapp/webhook'
    | '/api/public/calendar/oauth/callback'
    | '/api/public/email/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicInboundLeadRoute: typeof ApiPublicInboundLeadRoute
  ApiPublicCronCadenceTickRoute: typeof ApiPublicCronCadenceTickRoute
  ApiPublicCronCalendarSyncRoute: typeof ApiPublicCronCalendarSyncRoute
  ApiPublicCronMeetingFollowupRoute: typeof ApiPublicCronMeetingFollowupRoute
  ApiPublicCronRecoverLostRoute: typeof ApiPublicCronRecoverLostRoute
  ApiPublicCronReengageRoute: typeof ApiPublicCronReengageRoute
  ApiPublicOrbitWebhookRoute: typeof ApiPublicOrbitWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicCalendarOauthCallbackRoute: typeof ApiPublicCalendarOauthCallbackRoute
  ApiPublicEmailOauthCallbackRoute: typeof ApiPublicEmailOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agent-builder': {
      id: '/_authenticated/agent-builder'
      path: '/agent-builder'
      fullPath: '/agent-builder'
      preLoaderRoute: typeof AuthenticatedAgentBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-optimization': {
      id: '/_authenticated/agent-optimization'
      path: '/agent-optimization'
      fullPath: '/agent-optimization'
      preLoaderRoute: typeof AuthenticatedAgentOptimizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadences': {
      id: '/_authenticated/cadences'
      path: '/cadences'
      fullPath: '/cadences'
      preLoaderRoute: typeof AuthenticatedCadencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ideal-customer-profiles': {
      id: '/_authenticated/ideal-customer-profiles'
      path: '/ideal-customer-profiles'
      fullPath: '/ideal-customer-profiles'
      preLoaderRoute: typeof AuthenticatedIdealCustomerProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-calendar': {
      id: '/_authenticated/my-calendar'
      path: '/my-calendar'
      fullPath: '/my-calendar'
      preLoaderRoute: typeof AuthenticatedMyCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospecting': {
      id: '/_authenticated/prospecting'
      path: '/prospecting'
      fullPath: '/prospecting'
      preLoaderRoute: typeof AuthenticatedProspectingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/saas': {
      id: '/_authenticated/admin/saas'
      path: '/admin/saas'
      fullPath: '/admin/saas'
      preLoaderRoute: typeof AuthenticatedAdminSaasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ideal-customer-profiles/new': {
      id: '/_authenticated/ideal-customer-profiles/new'
      path: '/new'
      fullPath: '/ideal-customer-profiles/new'
      preLoaderRoute: typeof AuthenticatedIdealCustomerProfilesNewRouteImport
      parentRoute: typeof AuthenticatedIdealCustomerProfilesRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/settings/providers': {
      id: '/_authenticated/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AuthenticatedSettingsProvidersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/api/public/inbound-lead': {
      id: '/api/public/inbound-lead'
      path: '/api/public/inbound-lead'
      fullPath: '/api/public/inbound-lead'
      preLoaderRoute: typeof ApiPublicInboundLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cadence-tick': {
      id: '/api/public/cron/cadence-tick'
      path: '/api/public/cron/cadence-tick'
      fullPath: '/api/public/cron/cadence-tick'
      preLoaderRoute: typeof ApiPublicCronCadenceTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/calendar-sync': {
      id: '/api/public/cron/calendar-sync'
      path: '/api/public/cron/calendar-sync'
      fullPath: '/api/public/cron/calendar-sync'
      preLoaderRoute: typeof ApiPublicCronCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/meeting-followup': {
      id: '/api/public/cron/meeting-followup'
      path: '/api/public/cron/meeting-followup'
      fullPath: '/api/public/cron/meeting-followup'
      preLoaderRoute: typeof ApiPublicCronMeetingFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/recover-lost': {
      id: '/api/public/cron/recover-lost'
      path: '/api/public/cron/recover-lost'
      fullPath: '/api/public/cron/recover-lost'
      preLoaderRoute: typeof ApiPublicCronRecoverLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reengage': {
      id: '/api/public/cron/reengage'
      path: '/api/public/cron/reengage'
      fullPath: '/api/public/cron/reengage'
      preLoaderRoute: typeof ApiPublicCronReengageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orbit/webhook': {
      id: '/api/public/orbit/webhook'
      path: '/api/public/orbit/webhook'
      fullPath: '/api/public/orbit/webhook'
      preLoaderRoute: typeof ApiPublicOrbitWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/oauth/callback': {
      id: '/api/public/calendar/oauth/callback'
      path: '/api/public/calendar/oauth/callback'
      fullPath: '/api/public/calendar/oauth/callback'
      preLoaderRoute: typeof ApiPublicCalendarOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/oauth/callback': {
      id: '/api/public/email/oauth/callback'
      path: '/api/public/email/oauth/callback'
      fullPath: '/api/public/email/oauth/callback'
      preLoaderRoute: typeof ApiPublicEmailOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedIdealCustomerProfilesRouteChildren {
  AuthenticatedIdealCustomerProfilesNewRoute: typeof AuthenticatedIdealCustomerProfilesNewRoute
}

const AuthenticatedIdealCustomerProfilesRouteChildren: AuthenticatedIdealCustomerProfilesRouteChildren =
  {
    AuthenticatedIdealCustomerProfilesNewRoute:
      AuthenticatedIdealCustomerProfilesNewRoute,
  }

const AuthenticatedIdealCustomerProfilesRouteWithChildren =
  AuthenticatedIdealCustomerProfilesRoute._addFileChildren(
    AuthenticatedIdealCustomerProfilesRouteChildren,
  )

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsProvidersRoute: typeof AuthenticatedSettingsProvidersRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsProvidersRoute: AuthenticatedSettingsProvidersRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgentBuilderRoute: typeof AuthenticatedAgentBuilderRoute
  AuthenticatedAgentOptimizationRoute: typeof AuthenticatedAgentOptimizationRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCadencesRoute: typeof AuthenticatedCadencesRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedIdealCustomerProfilesRoute: typeof AuthenticatedIdealCustomerProfilesRouteWithChildren
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMyCalendarRoute: typeof AuthenticatedMyCalendarRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProspectingRoute: typeof AuthenticatedProspectingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAdminSaasRoute: typeof AuthenticatedAdminSaasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentBuilderRoute: AuthenticatedAgentBuilderRoute,
  AuthenticatedAgentOptimizationRoute: AuthenticatedAgentOptimizationRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCadencesRoute: AuthenticatedCadencesRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedIdealCustomerProfilesRoute:
    AuthenticatedIdealCustomerProfilesRouteWithChildren,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMyCalendarRoute: AuthenticatedMyCalendarRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProspectingRoute: AuthenticatedProspectingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAdminSaasRoute: AuthenticatedAdminSaasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicInboundLeadRoute: ApiPublicInboundLeadRoute,
  ApiPublicCronCadenceTickRoute: ApiPublicCronCadenceTickRoute,
  ApiPublicCronCalendarSyncRoute: ApiPublicCronCalendarSyncRoute,
  ApiPublicCronMeetingFollowupRoute: ApiPublicCronMeetingFollowupRoute,
  ApiPublicCronRecoverLostRoute: ApiPublicCronRecoverLostRoute,
  ApiPublicCronReengageRoute: ApiPublicCronReengageRoute,
  ApiPublicOrbitWebhookRoute: ApiPublicOrbitWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicCalendarOauthCallbackRoute: ApiPublicCalendarOauthCallbackRoute,
  ApiPublicEmailOauthCallbackRoute: ApiPublicEmailOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
